follow_controller:
  ros__parameters:
    target_topic: "/apriltag_pose"
    odom_topic: "/odom"
    cmd_topic: "/cmd_vel"
    control_frequency: 50.0
    kp_linear: 0.8
    kd_linear: 0.1
    kp_angular: 2.0
    kd_angular: 0.05
    goal_tolerance: 0.4
    goal_angle_tolerance: 0.1
    deadzone_theta: 0.25
    angular_offset: 0.06