servo_control:
  ros__parameters:
    freq:
      type: int
      default_value: 250
  
    micros_per_rad:
      type: double
      default_value: 648.984

    pins:
      front_left: 
        type: int_array
        default_value: [2, 3, 4]
      front_right: 
        type: int_array
        default_value: [14, 15, 17]
      back_left: 
        type: int_array
        default_value: [18, 27, 22]
      back_right: 
        type: int_array
        default_value: [2, 3, 4]

    # neutral_angles:
    #   type: double[]
    #   default_value:
    #     - [0, 0, 0]
    #     - [0, 0, 0]
    #     - [0, 0, 0]
    #     - [0, 0, 0]

    # servo_multipliers:
    #   type: int[]
    #   default_value:
    #     - [1, 1, -1]
    #     - [1, 1, -1]
    #     - [1, 1, -1]
    #     - [1, 1, -1]

    # servo_pwm_ranges:
    #   type: int[]
    #   default_value:
    #     - [680, 1340, 2320]
    #     - [680, 1340, 2320]
    #     - [800, 1550, 2320]
    #     - [680, 1340, 2320]
    #     - [680, 1340, 2320]
    #     - [680, 1340, 2320]
    #     - [680, 1340, 2320]
    #     - [680, 1340, 2320]
    #     - [680, 1340, 2320]
    #     - [680, 1340, 2320]
    #     - [680, 1340, 2320]
    #     - [680, 1340, 2320]

    # angle_constraints_degrees:
    #   type: double[]
    #   default_value:
    #     - [30.0, 150.0, 90.0]