/**:
  ros__parameters:
    image_topic: /snoopy/camera/image
    camera_info_topic: /camera/camera_info
    tag_size_m: 0.1385
    target_tag_id: -1

    use_camera_info_topic: true
    calibration_width: 1280
    calibration_height: 720
    camera_matrix: [1242.86002, 0.0, 578.436600, 0.0, 1238.06090, 322.452739, 0.0, 0.0, 1.0]
    distortion_coefficients: [-0.22467977, -0.14194663, -0.00117893, -0.00083476, 0.11091554]
