/**:
  ros__parameters:
    image_topic: /snoopy/camera/image
    camera_info_topic: /camera/camera_info
    tag_size_m: 0.1385
    target_tag_id: -1
    environment: 1 # 1: real, 0: sim
    camera_device_index: 0
    camera_read_period_ms: 100

    use_camera_info_topic: false
    calibration_width: 640
    calibration_height: 360
    camera_matrix: [622.399, 0.0, 288.983, 0.0, 619.952, 161.089, 0.0, 0.0, 1.0]
    distortion_coefficients: [-0.2233815,  -0.15420757, -0.00111942, -0.00090665,  0.13272059]
