inverse_kinematics_lifecycle_node:
  ros__parameters:
    joint_names:
      - LF_HIP_JOINT
      - LF_THIGH_JOINT
      - LF_THIGH_FOOT_JOINT
      - RF_HIP_JOINT
      - RF_THIGH_JOINT
      - RF_THIGH_FOOT_JOINT
      - LH_HIP_JOINT
      - LH_THIGH_JOINT
      - LH_THIGH_FOOT_JOINT
      - RH_HIP_JOINT
      - RH_THIGH_JOINT
      - RH_THIGH_FOOT_JOINT

    sim_theta_2_offset: -0.1784
    sim_theta_3_offset:  0.2617
    real_theta_2_offset: 0.5585
    real_theta_3_offset: 0.6807
    # real_theta_offsets: [IFL, OFL, IFR, OFR, IBL, OBL, IBR, OBR]
    real_theta_offsets: [0.8105, 0.7254, 0.8130, 0.8078, 0.7405, 0.7854, 0.7230, 0.8078]
    # real_theta_offsets: [0.6981, 0.7854, 0.5585, 0.6807, 0.7505, 0.7854, 0.7330, 0.8378]

    hip_offset_x: 0.02735
    hip_offset_z: 0.0012724

    h:  0.029523
    hu: 0.123522
    hl: 0.11643
